language: "node_js"

node_js:
  - 0.10
  - 0.11
  - 0.12

services:
  - rabbitmq # will start rabbitmq-server
  - mongodb # will start mongodb

branches:
  only:
    - v1.3

before_install:
  - npm install
  - sudo mkdir -p /var/log/push_server/ # To store log files
  - sudo chmod 777 /var/log/push_server/
  - cd src
  - cp config.js.ic config.js
  - cd ..

before_script:
  - cd src
  - export NODE_TLS_REJECT_UNAUTHORIZED="0"
  - node start.js > out & # Start the server
  - PID=$! # Save the PID
  - cd .. && sleep 5 # Wait for everything to start correctly

script:
  - make tests

after_script:
  - sleep 30
  - kill $PID
  - sleep 15
  - cd src
  - cat out
  - cd ..
  - make cloc

notifications:
   email:
      - fernando.rodriguezsela@telefonica.com
